# Generated by Django 5.1.7 on 2025-03-26 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0002_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fineslist',
            name='fine',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='player',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PlayerFines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_cost', models.IntegerField()),
                ('player_fine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_app.fineslist', to_field='fine')),
                ('player_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team_app.players')),
            ],
        ),
    ]
