# Generated by Django 5.1.7 on 2025-03-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0003_alter_fineslist_fine_alter_players_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerfines',
            name='player_paid',
            field=models.BooleanField(default=False),
        ),
    ]
